import LeanVMCircuits.Export

open LeanVMCircuits.Flock

structure Codegen where
  bindings : List (Nat × String)
  cache : List (Affine × String) := []
  lines : Array String := #[]
  next : Nat := 0

def fresh (state : Codegen) (operation : String) : String × Codegen :=
  let name := s!"w{state.next}"
  (name, { state with next := state.next + 1, lines := state.lines.push s!"    let {name} = {operation};" })

def emitAffine (affine : Affine) (state : Codegen) : Except String (String × Codegen) :=
  if let some name := state.cache.findSome? (fun (key, name) => if key = affine then some name else none) then
    .ok (name, state)
  else
    match affine with
    | .zero => .ok ("Wire::ZERO", state)
    | .one => .ok ("Wire::ONE", state)
    | .var index =>
      match state.bindings.findSome? (fun (key, name) => if key = index then some name else none) with
      | some name => .ok (name, state)
      | none => .error s!"unbound or forward variable {index}"
    | .xor left right => do
      let (leftName, state) ← emitAffine left state
      let (rightName, state) ← emitAffine right state
      let (name, state) := fresh state s!"c.xor({leftName}, {rightName})"
      return (name, { state with cache := (affine, name) :: state.cache })

def emit (artifact : Artifact) : Except String String := do
  let bindings := (List.range 64).flatMap fun i => [(i, s!"x[{i}]"), (64 + i, s!"y[{i}]")]
  let mut state : Codegen := { bindings }
  for row in artifact.rows do
    if state.bindings.any (fun (index, _) => index == row.output) then
      throw s!"duplicate product variable {row.output}"
    let (left, afterLeft) ← emitAffine row.left state
    let (right, afterRight) ← emitAffine row.right afterLeft
    let (name, afterProduct) := fresh afterRight s!"c.and({left}, {right})"
    state := { afterProduct with bindings := (row.output, name) :: afterProduct.bindings }
  let mut outputs : Array String := #[]
  for affine in artifact.outputs do
    let (name, afterOutput) ← emitAffine affine state
    state := afterOutput
    outputs := outputs.push name
  if outputs.size != 64 then throw "the exported doubleword must have 64 output bits"
  let header := "// Generated by verification/circuits/Generate.lean from Flock.adder64. Do not edit.\n\
    //! Clean-authored GF(2) circuits consumed by production instruction classes.\n\n\
    use crate::circuit::{Builder, Wire};\n\n\
    /// The checked wrapping-adder artifact, least-significant-bit products first.\n\
    pub fn wrapping_add64(c: &mut Builder, x: &[Wire; 64], y: &[Wire; 64]) -> [Wire; 64] {\n"
  let outputLines := (List.range 16).map fun line =>
    "        " ++ String.intercalate ", " ((List.range 4).map fun i => outputs[line * 4 + i]!) ++ ","
  return header ++ String.intercalate "\n" state.lines.toList ++ "\n    [\n" ++
    String.intercalate "\n" outputLines ++ "\n    ]\n}\n"

def main (args : List String) : IO Unit := do
  let [destination] := args | throw (IO.userError "usage: lake env lean --run Generate.lean <destination.rs>")
  match emit adder64 with
  | .error message => throw (IO.userError message)
  | .ok code =>
    IO.FS.writeFile destination code
    let format ← IO.Process.output {
      cmd := "rustfmt", args := #["--config-path", "../../rustfmt.toml", destination] }
    if format.exitCode != 0 then throw (IO.userError format.stderr)
