import LeanVMCircuits.AdderFamily

open LeanVMCircuits.Flock

structure Codegen where
  bindings : List (Nat × String)
  cache : List (Affine × String) := []
  lines : Array String := #[]
  next : Nat := 0

def fresh (state : Codegen) (operation : String) : String × Codegen :=
  let name := s!"w{state.next}"
  (name, { state with next := state.next + 1, lines := state.lines.push s!"    let {name} = {operation};" })

def emitAffine (affine : Affine) (state : Codegen) : Except String (String × Codegen) :=
  if let some name := state.cache.findSome? (fun (key, name) => if key = affine then some name else none) then
    .ok (name, state)
  else
    match affine with
    | .zero => .ok ("Wire::ZERO", state)
    | .one => .ok ("Wire::ONE", state)
    | .var index =>
      match state.bindings.findSome? (fun (key, name) => if key = index then some name else none) with
      | some name => .ok (name, state)
      | none => .error s!"unbound or forward variable {index}"
    | .xor left right => do
      let (leftName, state) ← emitAffine left state
      let (rightName, state) ← emitAffine right state
      let (name, state) := fresh state s!"c.xor({leftName}, {rightName})"
      return (name, { state with cache := (affine, name) :: state.cache })

def emit (name : String) (width : Nat) (withCarry : Bool) (artifact : Artifact) : Except String String := do
  let bindings := (List.range width).flatMap fun i => [(i, s!"x[{i}]"), (width + i, s!"y[{i}]")]
  let bindings := if withCarry then (2 * width, "carry_in") :: bindings else bindings
  let mut state : Codegen := { bindings }
  for row in artifact.rows do
    if state.bindings.any (fun (index, _) => index == row.output) then
      throw s!"duplicate product variable {row.output}"
    let (left, afterLeft) ← emitAffine row.left state
    let (right, afterRight) ← emitAffine row.right afterLeft
    let (name, afterProduct) := fresh afterRight s!"c.and({left}, {right})"
    state := { afterProduct with bindings := (row.output, name) :: afterProduct.bindings }
  let mut outputs : Array String := #[]
  for affine in artifact.outputs do
    let (name, afterOutput) ← emitAffine affine state
    state := afterOutput
    outputs := outputs.push name
  if outputs.size != width + (if withCarry then 1 else 0) then throw "unexpected exported output width"
  let parameter := if withCarry then ", carry_in: Wire" else ""
  let result := if withCarry then s!"([Wire; {width}], Wire)" else s!"[Wire; {width}]"
  let header := s!"/// The checked {name} artifact, least-significant-bit products first.\n\
    pub fn {name}(c: &mut Builder, x: &[Wire; {width}], y: &[Wire; {width}]{parameter}) -> {result} \{\n"
  let outputLines := (List.range (width / 4)).map fun line =>
    "        " ++ String.intercalate ", " ((List.range 4).map fun i => outputs[line * 4 + i]!) ++ ","
  let opening := if withCarry then "\n    (\n    [\n" else "\n    [\n"
  let closing := if withCarry then s!"\n    ],\n    {outputs[width]!},\n    )\n}\n" else "\n    ]\n}\n"
  return header ++ String.intercalate "\n" state.lines.toList ++ opening ++
    String.intercalate "\n" outputLines ++ closing

def emitProduction : Except String String := do
  let wrapping64 ← emit "wrapping_add64" 64 false adder64
  let wrapping32 ← emit "wrapping_add32" 32 false adder32
  let carry64 ← emit "add_with_carry64" 64 true carryAdder64
  return "// Generated by verification/circuits/Generate.lean from checked Flock artifacts. Do not edit.\n\
    //! Clean-authored GF(2) circuits consumed by production instruction classes.\n\n\
    use crate::circuit::{Builder, Wire};\n\n" ++ wrapping64 ++ "\n" ++ wrapping32 ++ "\n" ++ carry64

def main (args : List String) : IO Unit := do
  let [destination] := args | throw (IO.userError "usage: lake env lean --run Generate.lean <destination.rs>")
  match emitProduction with
  | .error message => throw (IO.userError message)
  | .ok code =>
    IO.FS.writeFile destination code
    let format ← IO.Process.output {
      cmd := "rustfmt", args := #["--config-path", "../../rustfmt.toml", destination] }
    if format.exitCode != 0 then throw (IO.userError format.stderr)
