[package]
name = "leanvm_aggregation_guest"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[features]
default = []
runtime = ["leanvm_guest/runtime"]

[dependencies]
leanvm_guest = { path = "../guest" }
leanvm_guest_claims = { path = "../guest_claims" }

[[example]]
name = "aggregate"
required-features = ["runtime"]
